Don
qkrxodud/dk-racing-car pull request #4
Opened 2023-06-02 05:44 UTC by kos5667

2023-06-02 16:17 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(text);
* split 할때 마다 pattern을 계산하는 것보다 하나의 인스턴스를 생성해 놓고 재사용하는건 어떨까요?!

2023-06-02 16:19 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +            }).sum();
* if-else 를쓰는 것보다 함수로 추출해서 리턴 하는 방식으로 줄여쓰는 것은 어떨까요?! 
[ https://dublin-java.tistory.com/47 ]

2023-06-02 16:24 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +            tokens = text.split(",|:");
* ",|:" 가 함수를 동작할때 마다 사용하는 것으로 보이는데, 하나의 인스턴스를 생성해 놓고 재사용하는것은 어떨까요?!

2023-06-02 16:26 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +            tokens = m.group(2).split(m.group(1));
*2와 1은 의미있는 상수같은데, 이것또한 인스턴스로 추출할수 있을것 같아요~.

2023-06-02 16:49 UTC, qkrxodud requested changes
안녕하세요. 던 
문자열계산기 잘 구현해 주신것 같아요.

그런데, 함수명이던지 if-else, 인스턴스 변수에대해서 안쓰고 있는 느낌이 들어서
작성해주시면 좀 더 좋은 방향으로 가지 않을까 싶어요.

내용 확인해주시고, 수정해주시면 머지하도록 할게요!.

2023-06-02 16:49 UTC, qkrxodud commented on src/test/java/level2/StringAddCalculatorTest.java
> +        assertThat(result).isEqualTo(0);
null 또는 빈 문자열을 테스트할 경우, @NullAndEmptySource라는 어노테이션을 활용해보는 걸 추천드립니다.
https://gmlwjd9405.github.io/2019/11/27/junit5-guide-parameterized-test.html

2023-06-02 16:49 UTC, qkrxodud commented on src/test/java/level2/StringAddCalculatorTest.java
> +        assertThat(result).isEqualTo(0);
null 또는 빈 문자열을 테스트할 경우, @NullAndEmptySource라는 어노테이션을 활용해보는 걸 추천드립니다.
https://gmlwjd9405.github.io/2019/11/27/junit5-guide-parameterized-test.html

2023-06-02 16:49 UTC, qkrxodud commented on src/test/java/level2/StringAddCalculatorTest.java
> +}
파일 끝에 개행을 추가해보면 어떨까요?
https://velog.io/@doondoony/posix-eol

2023-06-02 16:51 UTC, qkrxodud requested changes
안녕하세요. 던
문자열계산기 잘 구현해 주신것 같아요.

그런데, if-else, 인스턴스 변수에대해서 안쓰고 있는 느낌이 들어서
작성해주시면 좀 더 좋은 방향으로 가지 않을까 싶어요.

내용 확인해주시고, 수정해주시면 머지하도록 할게요!.

2023-06-06 10:17 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(text);
첫번째 답변이 이해가 잘 안되네요!! Pattern.compile 객체는 이미 final static 객체, 메서드이고 text를 파라미터로 받고 있는데 어떤걸 static final로 생성해야 될까요??

2023-06-06 10:30 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +            }).sum();
- 1자리를 메서드 한번 덜 태우려고 나눴는데 가독성이 떨어지는거 같아 지우는 쪽이 더 보기 좋은거 같습니다. ㅎㅎ

2023-06-06 14:22 UTC, qkrxodud approved these changes
안녕하세요. 던~ 잘 구현해 주셔서 머지 하였습니다.
몇 가지 사항만 확인해 주시고 넘으면 될 것 같습니다. 수고하셨어요 ~

2023-06-06 14:22 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +    private final static String CUSTOM_REGEX = "//(.)\n(.*)";
`private final static PATTERN = Pattern.compile(CUSTOM_REGEX);`
어차피 고정 값으로 전달해서 사용하는 부분이면 위와 같이 하면 어떨까 싶어서 전달드렸습니다 ~.

2023-06-06 14:22 UTC, qkrxodud commented on src/main/java/level2/StringAddCalculator.java
> +        }
``` java
private String[] createTokens (Matcher matcher) {
    if (matcher.find()) {
        return  matcher.group(NUM_TWO).split(matcher.group(NUM_ONE));
    }
    return tokens = text.split(REGEX);
}
```

`if` ~ `else`를 사용하면 가속성이 떨어지는 부분이 있습니다. 위와 같이 함수로 추출하여 리턴하는 방식으로 하면 좀 더 보기 수월할 것 같아요~.

2023-06-06 14:22 UTC, merged

2023-06-07 04:06 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +        Matcher m = Pattern.compile("//(.)\n(.*)").matcher(text);
수정 완료.

2023-06-07 04:06 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +            tokens = text.split(",|:");
수정 완료.

2023-06-07 04:06 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +            tokens = m.group(2).split(m.group(1));
수정 완료.

2023-06-07 04:07 UTC, kos5667 commented on src/test/java/level2/StringAddCalculatorTest.java
> +        assertThat(result).isEqualTo(0);
수정 완료.

2023-06-07 04:07 UTC, kos5667 commented on src/test/java/level2/StringAddCalculatorTest.java
> +}
수정 완료.

2023-06-07 04:25 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +    private final static String CUSTOM_REGEX = "//(.)\n(.*)";
수정완료

2023-06-07 04:25 UTC, kos5667 commented on src/main/java/level2/StringAddCalculator.java
> +        }
수정완료